DATASET_PATH = "/data/b22cs089/speech_PA2/task_2/"  
LANGUAGES = ["hindi", "bengali", "tamil", "marathi", "malayalam", "telugu", "kannada", "urdu", "punjabi", "gujarati"]  
# LANGUAGES = ["hindi"] 
N_MFCC = 13
HOP_LENGTH = 512
N_FFT = 2048
PLOT_PATH = "plots/"
RANDOM_STATE = 42
TEST_SIZE = 0.2
